# WARNING: DO NOT EDIT!
#
# This file was generated by plugin_template, and is managed by it. Please use
# './plugin-template --github pulp_python' to update this file.
#
# For more info visit https://github.com/pulp/plugin_template

import argparse
import os

from git import Repo

parser = argparse.ArgumentParser(formatter_class=argparse.RawTextHelpFormatter, description=helper)

parser.add_argument(
    "release_version",
    type=str,
    help="The version string for the release.",
)

args = parser.parse_args()

release_version_arg = args.release_version

release_path = os.path.dirname(os.path.abspath(__file__))
plugin_path = release_path.split("/.github")[0]

print(f"\n\nRepo path: {plugin_path}")
repo = Repo(plugin_path)

release_commit = None
# Look for a commit with the requested release version
for commit in repo.iter_commits():
    if f"Release {release_version_arg}\n" in commit.message:
        release_commit = commit
        release_version = release_version_arg
        break


